package inquire;
import java.awt.*;
import javax.swing.*;

public class Booking extends javax.swing.JFrame
{

    int i=0;//用于下文判断是出发地还是到达地
    int m;//用于下文赋值
    
    private JPanel imagePanel;      //用于下文设置背景
    private ImageIcon background1;  //用于下文设置背景
    private ImageIcon background2;  //用于下文设置背景
    
    public Booking(int i)//重写构造函数，得到来自Login_Interfa或Personal_Center的值，判断是新用户还是会员，打开对应的Result界面
    {
        initComponents();
        remove(p1);
        p1.setVisible(false);
        background1 = new ImageIcon("C:\\Users\\HAIER\\Documents\\NetBeansProjects\\inquire\\src\\newpackage\\Booking1.jpg");// 背景图片
        background2 = new ImageIcon("C:\\Users\\HAIER\\Documents\\NetBeansProjects\\inquire\\src\\newpackage\\Booking2.jpg");// Panel图片
        JLabel label = new JLabel(background1);
        label.setBounds(0, 0, 900,605);   
        imagePanel = (JPanel) getContentPane();         //设置背景
        imagePanel.setOpaque(false);
        imagePanel.setLayout(null);  
        getLayeredPane().setLayout(null);
        getLayeredPane().add(label, new Integer(Integer.MIN_VALUE));   
        
        JLabel a = new JLabel(background2);         //设置Panel背景
        a.setBounds(0, 0,600,291);
        p1.add(a,-1);
        m=i;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        p1 = new javax.swing.JPanel();
        q1 = new javax.swing.JLabel();
        q2 = new javax.swing.JLabel();
        q3 = new javax.swing.JLabel();
        q4 = new javax.swing.JLabel();
        q5 = new javax.swing.JLabel();
        q8 = new javax.swing.JLabel();
        q7 = new javax.swing.JLabel();
        q6 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        l4 = new javax.swing.JLabel();
        l6 = new javax.swing.JLabel();
        l7 = new javax.swing.JLabel();
        l1 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        l5 = new javax.swing.JLabel();

        setTitle("Booking");
        setResizable(false);

        p1.setPreferredSize(new java.awt.Dimension(653, 369));

        q1.setFont(new java.awt.Font("楷体", 3, 36)); // NOI18N
        q1.setText("北京");
        q1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                q1MouseClicked(evt);
            }
        });

        q2.setFont(new java.awt.Font("楷体", 3, 36)); // NOI18N
        q2.setText("上海");
        q2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                q2MouseClicked(evt);
            }
        });

        q3.setFont(new java.awt.Font("楷体", 3, 36)); // NOI18N
        q3.setText("广州");
        q3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                q3MouseClicked(evt);
            }
        });

        q4.setFont(new java.awt.Font("楷体", 3, 36)); // NOI18N
        q4.setText("成都");
        q4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                q4MouseClicked(evt);
            }
        });

        q5.setFont(new java.awt.Font("楷体", 3, 36)); // NOI18N
        q5.setText("深圳");
        q5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                q5MouseClicked(evt);
            }
        });

        q8.setFont(new java.awt.Font("楷体", 3, 36)); // NOI18N
        q8.setText("西安");
        q8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                q8MouseClicked(evt);
            }
        });

        q7.setFont(new java.awt.Font("楷体", 3, 36)); // NOI18N
        q7.setText("三亚");
        q7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                q7MouseClicked(evt);
            }
        });

        q6.setFont(new java.awt.Font("楷体", 3, 36)); // NOI18N
        q6.setText("海口");
        q6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                q6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout p1Layout = new javax.swing.GroupLayout(p1);
        p1.setLayout(p1Layout);
        p1Layout.setHorizontalGroup(
            p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(q1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(q5, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(q2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(q6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(q3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(q7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(q4, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                    .addComponent(q8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24))
        );
        p1Layout.setVerticalGroup(
            p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(q1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(q3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(q4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(q6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(q7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(q8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(91, 91, 91))
        );

        l3.setBackground(new java.awt.Color(255, 255, 255));
        l3.setFont(new java.awt.Font("楷体", 3, 30)); // NOI18N

        l4.setFont(new java.awt.Font("楷体", 3, 30)); // NOI18N

        l6.setFont(new java.awt.Font("Times New Roman", 3, 30)); // NOI18N
        l6.setText("Please select the starting point");
        l6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l6MouseClicked(evt);
            }
        });

        l7.setFont(new java.awt.Font("Times New Roman", 3, 30)); // NOI18N
        l7.setText("Please select the destination");
        l7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l7MouseClicked(evt);
            }
        });

        l1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/small picture.png"))); // NOI18N
        l1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l1MouseClicked(evt);
            }
        });

        l2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/small picture.png"))); // NOI18N
        l2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l2MouseClicked(evt);
            }
        });

        l5.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        l5.setText("Query");
        l5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(l6, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l7, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(l4, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(l1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(p1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(404, 404, 404)
                        .addComponent(l5)))
                .addContainerGap(154, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(l1)
                            .addComponent(l3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(l2)
                            .addComponent(l7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(l4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(l6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(p1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(l5)
                .addGap(57, 57, 57))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //下文的q1——q8MouseClicked，均为将地点显示在界面上，并用变量i，将第一次点击与第二次点击的地点分别显示在出发地与到达地上，并在选择后将Panel隐藏
    private void q1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_q1MouseClicked
        p1.setVisible(false);
        if(i==0)
        {
            String str=q1.getText();
            l3.setText(str);
            i++;
        }
        else if(i==1)
        {
            String str=q1.getText();
            l4.setText(str);
        }
       
        
    }//GEN-LAST:event_q1MouseClicked

    private void q2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_q2MouseClicked
        p1.setVisible(false);
        if(i==0)
        {
            String str=q2.getText();
            l3.setText(str);
            i++;
        }
        else if(i==1)
        {
            String str=q2.getText();
            l4.setText(str);
        }
    }//GEN-LAST:event_q2MouseClicked

    private void q3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_q3MouseClicked
        p1.setVisible(false);
        if(i==0)
        {
            String str=q3.getText();
            l3.setText(str);
            i++;
        }
        else if(i==1)
        {
            String str=q3.getText();
            l4.setText(str);
        }
    }//GEN-LAST:event_q3MouseClicked

    private void q4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_q4MouseClicked
        p1.setVisible(false);
        if(i==0)
        {
            String str=q4.getText();
            l3.setText(str);
            i++;
        }
        else if(i==1)
        {
            String str=q4.getText();
            l4.setText(str);
        }
    }//GEN-LAST:event_q4MouseClicked

    private void q5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_q5MouseClicked
        p1.setVisible(false);
        if(i==0)
        {
            String str=q5.getText();
            l3.setText(str);
            i++;
        }
        else if(i==1)
        {
            String str=q5.getText();
            l4.setText(str);
        }
    }//GEN-LAST:event_q5MouseClicked

    private void q8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_q8MouseClicked
        p1.setVisible(false);
        if(i==0)
        {
            String str=q8.getText();
            l3.setText(str);
            i++;
        }
        else if(i==1)
        {
            String str=q8.getText();
            l4.setText(str);
        }
    }//GEN-LAST:event_q8MouseClicked

    private void q7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_q7MouseClicked
        p1.setVisible(false);
        if(i==0)
        {
            String str=q7.getText();
            l3.setText(str);
            i++;
        }
        else if(i==1)
        {
            String str=q7.getText();
            l4.setText(str);
        }                             
    }//GEN-LAST:event_q7MouseClicked

    private void q6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_q6MouseClicked
        p1.setVisible(false);
        if(i==0)
        {
            String str=q6.getText();
            l3.setText(str);
            i++;
        }
        else if(i==1)
        {
            String str=q6.getText();
            l4.setText(str);
        }                         
    }//GEN-LAST:event_q6MouseClicked

    private void l5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l5MouseClicked

            if(l3.getText().length()==0)
            {
                JOptionPane.showMessageDialog(null,"请选择出发地！","错误！！！",JOptionPane.ERROR_MESSAGE);    //如果没有选择出发地，显示错误
            }
            else if(l4.getText().length()==0)
            {
                JOptionPane.showMessageDialog(null,"请选择到达地！","错误！！！",JOptionPane.ERROR_MESSAGE);    //如果没有选择到达地，显示错误
            }
            else if(l4.getText()==l3.getText())
            {
               JOptionPane.showMessageDialog(null,"出发地不能与到达地一致！","错误！！！",JOptionPane.ERROR_MESSAGE);   //如果出发点与到达地一样，显示错误
            }   
            else
            {
                if(m==0)
                {
                    Result1 w=new Result1(l3.getText(),l4.getText()); //会员，如果出发点与到达地选择正确，打开Result1界面，并关闭此Booking界面
                    w.show();
                    w.setLocationRelativeTo(null);
                    dispose();
                }
                else if(m==1)
                {
                    Result2 w=new Result2(l3.getText(),l4.getText()); //新用户，如果出发点与到达地选择正确，打开Result2界面，并关闭此Booking界面
                    w.show();
                    w.setLocationRelativeTo(null);
                    dispose();
                }
           
            }
    }//GEN-LAST:event_l5MouseClicked

    private void l6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_l6MouseClicked

    private void l7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_l7MouseClicked

    private void l1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l1MouseClicked
        add(p1);            //将隐藏的Panel，显示出来
        p1.setVisible(true);
    }//GEN-LAST:event_l1MouseClicked

    private void l2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l2MouseClicked

        if(l3.getText().length()==0)
        {
            JOptionPane.showMessageDialog(null,"请先选择出发地！","错误！！！",JOptionPane.ERROR_MESSAGE);//如果先选择到达地，显示错误
        }
        else
        {
            add(p1);            //将隐藏的Panel，显示出来
            p1.setVisible(true);
        }
    }//GEN-LAST:event_l2MouseClicked

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() 
            {

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel l5;
    private javax.swing.JLabel l6;
    private javax.swing.JLabel l7;
    private javax.swing.JPanel p1;
    private javax.swing.JLabel q1;
    private javax.swing.JLabel q2;
    private javax.swing.JLabel q3;
    private javax.swing.JLabel q4;
    private javax.swing.JLabel q5;
    private javax.swing.JLabel q6;
    private javax.swing.JLabel q7;
    private javax.swing.JLabel q8;
    // End of variables declaration//GEN-END:variables
}
